(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const track=(event,route)=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,route});};
  const menu=document.querySelector('.menu-toggle');
  menu?.addEventListener('click',()=>{const open=document.querySelector('.nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
  const cards=[...document.querySelectorAll('.catalog-product-card')];
  document.querySelectorAll('.catalog-product-video video').forEach(video=>{video.controls=true;const initialSource=video.querySelector('source');initialSource.src=initialSource.dataset.src;video.addEventListener('pointerenter',()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const source=video.querySelector('source');if(!source.src){source.src=source.dataset.src;video.load();}video.play().catch(()=>{});});video.addEventListener('pointerleave',()=>video.pause());video.addEventListener('play',()=>{const source=video.querySelector('source');if(!source.src){source.src=source.dataset.src;video.load();video.play().catch(()=>{});}});});
  if(cards.length){const more=document.createElement('button');more.className='button outline catalog-expand';more.textContent='VIEW ALL DESIGNS ↓';document.querySelector('#catalog-product-grid').after(more);more.addEventListener('click',()=>{const expanded=document.querySelector('#catalog-product-grid').classList.toggle('expanded');more.textContent=expanded?'SHOW FEWER ↑':'VIEW ALL DESIGNS ↓';});document.querySelectorAll('.catalog-filter').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('is-active')));b.addEventListener('click',()=>{document.querySelectorAll('.catalog-filter').forEach(x=>{x.classList.toggle('is-active',x===b);x.setAttribute('aria-pressed',String(x===b));});cards.forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter);document.querySelector('#catalog-product-grid').classList.add('expanded');more.hidden=b.dataset.filter!=='all';});});}
  function routeFor(text){if(/sell|buy my|worth|payout/i.test(text))return 'selling';if(/repair|broken|broke|resiz|battery|fix|engraving|restore/i.test(text))return 'repair';if(/financ|leasing|payment plan|credit|acima|snap/i.test(text))return 'financing';if(/visit|appointment|hours|directions|store location/i.test(text))return 'visit';if(/custom|design|make|create|initial|nameplate/i.test(text))return 'custom';return 'shopping';}
  $('route-form')?.addEventListener('submit',async e=>{e.preventDefault();const idea=$('intent').value.trim();if(!idea){$('route-status').textContent='Tell Astra what you need, or choose a path below.';return;}const button=e.currentTarget.querySelector('button');button.disabled=true;$('route-status').textContent='Finding your next step…';let route=routeFor(idea);try{const res=await fetch('/api/astra-assist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea}),signal:AbortSignal.timeout(10000)});const data=await res.json();if(res.ok&&['custom','shopping','repair','selling','financing','visit'].includes(data.route))route=data.route;}catch(_){}track('astra_route_selected',route);try{sessionStorage.setItem('hog-astra-intent',JSON.stringify({route,idea}));}catch(_){}location.href='/astra-studio.html?route='+route;});
  const form=$('studio-form');if(!form)return;
  const labels={custom:['THE VISION','Describe your vision','A piece with a point of view.'],shopping:['THE PIECE','What are you looking for?','Find your next signature.'],repair:['THE REPAIR','What happened to your jewelry?','Keep the story going.'],selling:['THE ITEM','What would you like to sell?','Your next beginning.'],financing:['YOUR OPTIONS','What piece or purchase are you considering?','Explore your options.'],visit:['THE VISIT','What would you like help with in store?','Let’s meet.']};
  const details={shopping:'Preferred type, style, length / width, karat, budget or product name / SKU',repair:'Jewelry type, visible damage, when it happened and requested service',selling:'Gold: karat and approximate weight if known. Watch: brand, model, condition, box / papers if available',financing:'Preferred provider or questions. Do not include SSNs, bank or credit information',visit:'Reason for visit and any pieces you would like to discuss'};
  let step=0,reference='',concept=null,busy=false,epoch=0,submitted=false;
  const started=Date.now();
  const field=n=>form.elements.namedItem(n);
  const touched=new Set();
  function infer(){
    if(route()!=='custom')return;
    const text=$('idea').value;
    const set=(name,value)=>{if(value&&!touched.has(name)&&[...(field(name).options||[])].some(x=>x.value===value))field(name).value=value;};
    const type=/\b(pendant|ring|nameplate|bracelet|chain|earrings?)\b/i.exec(text);
    if(type)set('piece',type[1].toLowerCase().startsWith('earring')?'Earrings':type[1][0].toUpperCase()+type[1].slice(1).toLowerCase());
    const karat=/\b(10|14|18)\s*k\b/i.exec(text);
    if(karat){const color=/white gold/i.test(text)?'White':/rose gold/i.test(text)?'Rose':'Yellow';set('metal',karat[1]==='14'?'14K '+color+' Gold':karat[1]+'K Gold');}
    if(/platinum/i.test(text))set('metal','Platinum');
    if(/lab[ -]grown|lab diamonds/i.test(text))set('stones','Lab-grown diamonds');else if(/natural diamonds/i.test(text))set('stones','Natural diamonds');else if(/no stones|gold only/i.test(text))set('stones','No stones / gold only');else if(/gemstones|sapphire|ruby|emerald/i.test(text))set('stones','Colored gemstones');
    const budget=/(?:budget\s*(?:of|around|about|is|:)?\s*\$?([\d,]+(?:\.\d{1,2})?)|\$([\d,]+(?:\.\d{1,2})?))/i.exec(text);
    if(budget&&!touched.has('budget'))field('budget').value='$'+(budget[1]||budget[2]).replace(/,+$/,'');
    const size=/\b(?:size\s*\d+(?:\.\d+)?|\d+(?:\.\d+|½|¼|¾)?\s*(?:inch(?:es)?|mm|cm))\b/i.exec(text);
    if(size&&!touched.has('size_dimensions'))field('size_dimensions').value=size[0];
  }
  function values(){return Object.fromEntries(new FormData(form));}
  const route=()=>$('route').value;
  function spec(){const v=values();return {piece:v.piece,metal:v.metal,stones:v.stones,budget:v.budget,size:v.size_dimensions,notes:v.idea};}
  function refresh(){const v=values(),r=route();$('brief-title').textContent=labels[r][2];$('idea-label').textContent=labels[r][1];$('idea').placeholder=r==='custom'?'A 14K pendant with my initials, about 2½ inches…':'Tell us a little about what you need…';$('custom-fields').hidden=r!=='custom';$('service-fields').hidden=r==='custom';$('studio-finance').hidden=r!=='financing';$('concept-wrap').hidden=r!=='custom';$('inspiration-wrap').hidden=!['custom','repair','selling','shopping'].includes(r);$('service-detail-label').textContent=details[r]||'Additional details';$('brief-idea').textContent=v.idea||'Your request starts here.';const rows=r==='custom'?[['Piece',v.piece],['Metal',v.metal],['Stones',v.stones],['Budget',v.budget||'To discuss'],['Dimensions',v.size_dimensions||'To discuss']]:[['Request',field('route').selectedOptions[0].textContent],['Details',v.details||'To discuss']];if(v.contact_time)rows.push(['Preferred time',v.contact_time]);if(reference&&!$('inspiration-wrap').hidden)rows.push(['Inspiration','Image attached']);if(concept)rows.push(['AI concept',concept.conceptId]);$('brief-details').replaceChildren();rows.forEach(([key,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;$('brief-details').append(dt,dd);});}
  function show(){document.querySelectorAll('.step').forEach(x=>x.hidden=Number(x.dataset.step)!==step);$('step-counter').textContent='0'+(step+1)+' / 03';$('step-name').textContent=step===0?labels[route()][0]:step===1?'THE DETAILS':'THE HANDOFF';$('previous').hidden=step===0;$('next').hidden=step===2;$('send').hidden=step!==2;refresh();}
  function invalidate(){epoch++;if(concept){concept=null;$('concept-image').hidden=true;$('revise').hidden=true;$('concept-status').textContent='Your brief changed. Generate a new concept to match it.';}}
  form.addEventListener('input',e=>{if(['piece','metal','stones','budget','size_dimensions'].includes(e.target.name))touched.add(e.target.name);if(['idea','piece','metal','stones','budget','size_dimensions','route'].includes(e.target.name))invalidate();if(e.target.name==='idea')infer();refresh();});
  $('route').addEventListener('change',()=>{invalidate();step=0;show();track('astra_route_selected',route());});
  $('next').addEventListener('click',()=>{if(step===0&&!$('idea').value.trim()){$('idea').reportValidity();$('idea').focus();return;}step=Math.min(2,step+1);show();document.querySelector('.workspace').scrollIntoView({block:'start',behavior:'smooth'});document.querySelector('.step:not([hidden]) input, .step:not([hidden]) select')?.focus();track('astra_step_completed',route());});
  $('previous').addEventListener('click',()=>{step=Math.max(0,step-1);show();});
  async function json(url,body,timeout=35000){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'This service is unavailable. Please call (631) 264-6610.');return data;}
  $('assist').addEventListener('click',async()=>{if(!$('idea').value.trim()){$('assist-status').textContent='Add your idea first, then Astra can help with the missing details.';return;}const b=$('assist');b.disabled=true;$('assist-status').textContent='Astra is reviewing your description…';try{const d=await json('/api/chat',{messages:[{role:'user',content:'Help qualify this '+route()+' request. Ask only up to two missing questions. Do not repeat questions already answered. Brief: '+JSON.stringify(spec())}],context:{path:'/astra-studio.html'}});$('assist-status').textContent=d.reply;}catch(e){$('assist-status').textContent='Astra is unavailable right now. You can still complete your brief and send it to our jewelers.';}finally{b.disabled=false;}});
  $('inspiration').addEventListener('change',async()=>{const file=$('inspiration').files[0];if(!file)return;reference='';invalidate();$('file-status').textContent='Preparing your inspiration…';try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Choose a JPEG, PNG or WebP image no larger than 5 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();reference=canvas.toDataURL('image/jpeg',.82);if(reference.length>800000)throw new Error('This image is too detailed. Please choose a smaller image.');$('reference-image').src=reference;document.querySelector('.reference').hidden=false;$('file-status').textContent='Inspiration attached to your draft. It has not been sent yet.';}catch(e){reference='';$('inspiration').value='';document.querySelector('.reference').hidden=true;$('file-status').textContent=e.message;}refresh();});
  $('remove-reference').addEventListener('click',()=>{reference='';$('inspiration').value='';$('reference-image').removeAttribute('src');document.querySelector('.reference').hidden=true;$('file-status').textContent='Inspiration removed.';invalidate();refresh();});
  async function generate(){if(busy||submitted)return;if(!$('idea').value.trim()){$('concept-status').textContent='Describe your idea before generating a concept.';return;}if(field('piece').value==='Not sure yet'){$('concept-status').textContent='Choose a jewelry type in the details step before generating.';return;}busy=true;const version=epoch;$('generate').disabled=true;$('revise').disabled=true;$('concept-status').textContent='Creating a concept from your brief. This may take a few minutes…';try{const d=await json('/api/design',{...spec(),referenceImage:reference,website:''},300000);if(version!==epoch){$('concept-status').textContent='Your brief changed during generation. Generate again to match the current details.';return;}concept=d;$('concept-image').src=d.image;$('concept-image').hidden=false;$('revise').hidden=false;$('concept-status').textContent='Concept ready. For inspiration only; our jewelers review the actual design.';track('astra_concept_created',route());refresh();}catch(e){$('concept-status').textContent=e.message+' You can still send your brief without a concept.';}finally{busy=false;$('generate').disabled=submitted;$('revise').disabled=submitted;}}
  $('generate').addEventListener('click',generate);$('revise').addEventListener('click',generate);
  form.addEventListener('submit',async e=>{e.preventDefault();if(step!==2||submitted)return;if(busy){$('submit-status').textContent='Please wait for your concept to finish, then send your brief.';return;}const v=values();if(!String(v.name).trim()||(!String(v.email).trim()&&!String(v.phone).trim())){$('submit-status').textContent='Please enter your name and an email or phone number.';$('submit-status').focus();return;}if(!field('consent').checked){$('submit-status').textContent='Please confirm contact consent.';return;}const r=route(),custom=r==='custom';const type=custom?'custom_jewelry':r==='shopping'?'product_inquiry':'service';const payload={leadType:type,service:r,source:'astra_studio',page:'/astra-studio.html',name:v.name,email:v.email,phone:v.phone,consent:true,website:v.website,elapsed:(Date.now()-started)/1000,message:v.idea,details:custom?'':v.details,contact_time:v.contact_time,request_summary:[field('route').selectedOptions[0].textContent,v.idea,...(custom?[v.piece,v.metal,v.stones,v.budget,v.size_dimensions]:[v.details]),v.contact_time].filter(Boolean).join(' · '),approval_status:'staff_review_required',...(custom?{piece:v.piece,metal:v.metal,stones:v.stones,budget:v.budget,size_dimensions:v.size_dimensions,design_notes:v.idea}:{}),...(reference&&!$('inspiration-wrap').hidden?{inspiration_image:reference}:{}),...(custom&&concept?{concept_id:concept.conceptId,concept_image_url:concept.imageUrl}:{}),};$('send').disabled=true;$('submit-status').textContent='Sending your request securely…';try{const d=await json('/api/leads',payload);if(!d.success||!d.leadId)throw new Error('We could not confirm receipt. Please call (631) 264-6610.');$('submit-status').textContent='Received by Hands of Gold. Reference: '+d.leadId+'. Our team will review your request. No order, appointment, price or completion date has been confirmed.';submitted=true;form.querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=true);$('generate').disabled=true;$('revise').disabled=true;track('astra_lead_received',r);$('submit-status').focus();}catch(e){$('submit-status').textContent=e.message+' Your draft is still here; retry or call (631) 264-6610.';$('send').disabled=false;track('astra_lead_failed',r);}});
  const params=new URLSearchParams(location.search);if(labels[params.get('route')])$('route').value=params.get('route');
  try{const cached=JSON.parse(sessionStorage.getItem('hog-astra-intent')||'null');if(cached&&cached.route===route()){$('idea').value=String(cached.idea).slice(0,1200);sessionStorage.removeItem('hog-astra-intent');}}catch(_){}
  infer();show();track('astra_studio_opened',route());
  fetch('/api/design?probe=1',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(data&&data.available===false){$('generate').disabled=true;$('concept-status').textContent='AI concept previews are unavailable here. You can still send your inspiration and brief to our jewelers.';}}).catch(()=>{});
})();