(() => {
'use strict';
if(document.getElementById('astra-launch'))return;
const css=document.createElement('link');css.rel='stylesheet';css.href='/astra-chat.css';document.head.append(css);
const root=document.createElement('div');root.id='astra-chat';
root.innerHTML=`<button id="astra-launch" aria-controls="astra-panel" aria-expanded="false">✦ Chat with Astra</button>
<section id="astra-panel" role="dialog" aria-modal="true" aria-labelledby="astra-title" hidden>
<header><div><strong id="astra-title">Astra</strong><span>Your AI jewelry concierge</span></div><button id="astra-close" aria-label="Close Astra chat">×</button></header>
<div id="astra-scroll"><p class="astra-intro">Find your next piece. Create something personal. Let’s get you started.</p>
<p class="astra-note">AI guidance. Staff confirm prices, availability and commitments. Messages are sent to our AI provider and kept in this browser tab for up to two hours. Don’t share payment or sensitive personal details. <a href="/privacy.html">Privacy</a></p>
<div id="astra-choices" aria-label="What can Astra help with?"></div><div id="astra-messages" role="log" aria-live="polite" aria-label="Conversation with Astra"></div>
<div id="astra-links" aria-label="Your next steps"></div>
<form id="astra-lead" hidden><h3>Let our team help</h3><p>Review your request below. We’ll include the recent conversation so you don’t have to start over.</p>
<label>Name<input name="name" required maxlength="160" autocomplete="name"></label><label>Email<input name="email" type="email" maxlength="254" autocomplete="email"></label><label>Phone<input name="phone" type="tel" maxlength="30" autocomplete="tel"></label><p class="astra-note">Include either email or phone.</p>
<label>Request<textarea name="request" required maxlength="1200" rows="3"></textarea></label>
<label class="astra-consent"><input name="consent" type="checkbox" required> <span>I agree to the <a href="/terms.html">Terms</a> and <a href="/privacy.html">Privacy Policy</a> and consent to Hands of Gold contacting me about this request.</span></label>
<button type="submit">Send request</button><p id="astra-lead-status" role="status"></p></form></div>
<div class="astra-team"><button id="astra-handoff">Send to our team</button><a href="tel:6312646610">Call the store</a></div>
<form id="astra-compose"><label class="astra-sr" for="astra-input">Message Astra</label><textarea id="astra-input" maxlength="1200" rows="2" placeholder="What are you looking for?" required></textarea><button type="submit" id="astra-send">Send</button></form><p id="astra-status" role="status"></p>
</section>`;
document.body.append(root);
const $=id=>document.getElementById(id),panel=$('astra-panel'),messages=[];let busy=false,route='shopping',lastFocus=null,oldOverflow='',background=[],selectedProduct=null;
const routes={shopping:{label:'Shop jewelry',prompt:'Help me find a piece of jewelry.',links:[['Browse jewelry','/index.html#featured-products'],['Monaci Cuban collection','/classic-cuban-collection.html']]},custom:{label:'Create custom',prompt:'I want to create custom jewelry.',links:[['Open Custom Studio','/custom-jewelry.html'],['Design Grillz','/grillz.html#studio']]},repairs:{label:'Repair a piece',prompt:'I need help with a jewelry or watch repair.',links:[['Repair request','/jewelry-repair.html#request']]},selling:{label:'Sell gold / watches',prompt:'I want to sell gold or a watch.',links:[['Gold calculator','/index.html#sell-watches-gold'],['Sell a watch','/sell-watch.html#request']]},financing:{label:'Payment options',prompt:'What financing or payment options can I apply for?',links:[]},visit:{label:'Plan a visit',prompt:'I would like to visit the store. What are your hours?',links:[['Store & directions','/index.html#visit']]}};
// These are the store's existing provider application URLs, copied from its menu.
const providerLinks=[["Snap Finance","https://apply.snapfinance.com/snap-com/landing?paramId=3w%2FEWVFzVGfi1E%2BWcXyAQsljS1AwpiW%2FaDIok%2F6DV5OeOs3FN4ZsDmWkSyyb89qs4onMkaC3QhjXhMrTA%2FKxEz7nBBAhljmUQ3yem7XAML8%3D&source=QR_CODE&merchantId=490293817&lang=en"],["Acima Leasing","https://apply.acima.com/auth/v2/otp-start?app_id=lo&location_guid=loca-13d42b3d-d60f-4ca0-8a25-a91ef62ad26c&utm_campaign=generic_qr&utm_content=pop&utm_medium=merchant&utm_source=qr&lang=en"]];
routes.financing.links=providerLinks;
function save(){try{sessionStorage.setItem('hog-astra-chat',JSON.stringify({at:Date.now(),messages:messages.slice(-16),selectedProduct}));}catch(_){}}
function track(event){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,route});}
function showLinks(){const box=$('astra-links');box.replaceChildren();for(const [label,url] of routes[route].links){const a=document.createElement('a');a.textContent=label;a.href=url;if(url.startsWith('https:')){a.target='_blank';a.rel='noopener noreferrer';}box.append(a);}}
function infer(text){if(/sell|buy my|payout|vender/i.test(text))return 'selling';if(/repair|broken|resiz|battery|fix|repar/i.test(text))return 'repairs';if(/financ|payment|credit|acima|snap|leasing/i.test(text))return 'financing';if(/custom|design|make|nameplate|grill|personaliz/i.test(text))return 'custom';if(/visit|appointment|hours|directions|ubicaci|horario/i.test(text))return 'visit';if(/shop|buy|ring|chain|bracelet|pendant|earring/i.test(text))return 'shopping';return route;}
function validProduct(p){return p&&typeof p.title==='string'&&typeof p.description==='string'&&/^\/products\/[a-z0-9-]+\.html$/.test(p.url)&&/^\/posters\/[a-z0-9-]+\.jpg$/.test(p.image);}
function cards(products){const wrap=document.createElement('div');wrap.className='astra-products';for(const product of products.filter(validProduct).slice(0,2)){const card=document.createElement('article');card.className='astra-product';const image=document.createElement('img');image.src=product.image;image.alt=product.title;image.loading='lazy';image.width=320;image.height=240;image.onerror=()=>image.remove();const title=document.createElement('h3');title.textContent=product.title;const description=document.createElement('p');description.textContent=product.description;const note=document.createElement('p');note.className='astra-note';note.textContent='Ask our team for current price and availability.';const details=document.createElement('a');details.href=product.url;details.textContent='View details';const request=document.createElement('button');request.type='button';request.textContent='Request this piece';request.setAttribute('aria-label','Request '+product.title);request.onclick=()=>{selectedProduct=product;route='shopping';save();const form=$('astra-lead');form.hidden=false;const chosen='Selected piece: '+product.title+' ('+product.url+')';if(!form.elements.request.value)form.elements.request.value=messages.filter(m=>m.role==='user').map(m=>m.content).join('\n').slice(0,850);form.elements.request.value=form.elements.request.value.replace(/^Selected piece:.*\n?/gm,'');form.elements.request.value=(chosen+'\n'+form.elements.request.value).slice(0,1200);form.elements.name.focus();track('astra_product_selected');};const actions=document.createElement('div');actions.append(details,request);card.append(image,title,description,note,actions);wrap.append(card);}if(wrap.children.length)$('astra-messages').append(wrap);}
function bubble(role,text){const p=document.createElement('p');p.className='astra-message '+role;p.textContent=text;$('astra-messages').append(p);$('astra-scroll').scrollTop=$('astra-scroll').scrollHeight;}
function setOpen(open){if(open===!panel.hidden)return;panel.hidden=!open;$('astra-launch').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';background=[...document.body.children].filter(e=>e!==root).map(e=>[e,e.inert]);background.forEach(([e])=>e.inert=true);$('astra-input').focus();track('astra_chat_open');}else{background.forEach(([e,value])=>e.inert=value);document.body.style.overflow=oldOverflow;lastFocus?.focus();}}
$('astra-launch').onclick=()=>setOpen(true);$('astra-close').onclick=()=>setOpen(false);
panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);}if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,a,input,textarea')].filter(e=>!e.disabled&&e.getClientRects().length);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
async function send(text){if(busy||!text.trim())return;text=text.trim().slice(0,1200);route=infer(text);showLinks();messages.push({role:'user',content:text});save();bubble('user',text);$('astra-input').value='';busy=true;$('astra-send').disabled=true;$('astra-choices').querySelectorAll('button').forEach(b=>b.disabled=true);$('astra-status').textContent='Astra is thinking…';try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:messages.slice(-16).map(({role,content})=>({role,content})),context:{pageTitle:document.title,path:location.pathname}}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok||!d.reply)throw new Error(d.error||'Astra is unavailable right now.');const products=(d.products||[]).filter(validProduct).slice(0,2);messages.push({role:'assistant',content:d.reply,products});save();bubble('assistant',d.reply);cards(products);$('astra-scroll').scrollTop=$('astra-scroll').scrollHeight;$('astra-status').textContent='';track('astra_chat_reply');}catch(e){$('astra-status').textContent=(e.name==='TimeoutError'?'Astra is taking longer than expected.':e.message)+' You can send your request to our team below or call the store.';}finally{busy=false;$('astra-send').disabled=false;$('astra-choices').querySelectorAll('button').forEach(b=>b.disabled=false);}}
for(const [key,item] of Object.entries(routes)){const b=document.createElement('button');b.type='button';b.textContent=item.label;b.onclick=()=>{route=key;send(item.prompt);};$('astra-choices').append(b);}
$('astra-compose').onsubmit=e=>{e.preventDefault();send($('astra-input').value);};
$('astra-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(e.target.value);}});
$('astra-handoff').onclick=()=>{const form=$('astra-lead');form.hidden=false;if(!form.elements.request.value)form.elements.request.value=((selectedProduct?'Selected piece: '+selectedProduct.title+' ('+selectedProduct.url+')\n':'')+messages.filter(m=>m.role==='user').map(m=>m.content).join('\n')).slice(0,1200);form.elements.name.focus();};
$('astra-lead').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),status=$('astra-lead-status');if(!form.elements.email.value.trim()&&!form.elements.phone.value.trim()){status.textContent='Please include an email address or phone number.';return;}button.disabled=true;status.textContent='Sending your request…';const transcript=messages.map(m=>(m.role==='user'?'Customer: ':'Astra (AI, unverified): ')+m.content).join('\n').slice(-2400);try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:'astra_chat',product:selectedProduct&&form.elements.request.value.includes(selectedProduct.title)?selectedProduct.title:'',productSlug:selectedProduct&&form.elements.request.value.includes(selectedProduct.title)?selectedProduct.url:'',leadType:route==='shopping'?'product_inquiry':'service',service:route,page:location.pathname,name:form.elements.name.value.trim(),email:form.elements.email.value.trim(),phone:form.elements.phone.value.trim(),consent:form.elements.consent.checked,request_summary:form.elements.request.value,message:'Customer request: '+form.elements.request.value.slice(0,500)+'\nConversation (AI replies require staff review):\n'+transcript,website:''}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok||!d.success||!d.leadId)throw new Error(d.error||'Receipt could not be confirmed.');status.textContent='Received by Hands of Gold. Reference '+d.leadId+'. Our team will follow up. Prices, orders and appointments require staff confirmation.';form.querySelectorAll('input,textarea,button').forEach(e=>e.disabled=true);track('astra_lead_received');}catch(err){status.textContent=err.message+' Your details are still here. Please retry or call (631) 264-6610.';button.disabled=false;}};
try{const cached=JSON.parse(sessionStorage.getItem('hog-astra-chat')||'null');if(cached&&Date.now()-cached.at<7200000&&Array.isArray(cached.messages)){for(const m of cached.messages.slice(-16)){if(!['user','assistant'].includes(m.role)||typeof m.content!=='string')continue;const products=Array.isArray(m.products)?m.products.filter(validProduct).slice(0,2):[];messages.push({role:m.role,content:m.content.slice(0,2200),products});bubble(m.role,m.content.slice(0,2200));if(m.role==='assistant')cards(products);}if(validProduct(cached.selectedProduct))selectedProduct=cached.selectedProduct;const last=messages.filter(m=>m.role==='user').at(-1);if(last)route=infer(last.content);}}catch(_){}
showLinks();
})();
